FROM liferay/portal:7.4.3.112-ga112

ENV LIFERAY_SETUP_WIZARD_ENABLED=false
ENV LIFERAY_DEFAULT_ADMIN_PASSWORD=test

ENV LIFERAY_JAVASCRIPT_FAST_LOAD=false
ENV LIFERAY_THEME_CSS_FAST_LOAD=false
ENV LIFERAY_MINIFIER_ENABLED=false

ENV CATALINA_OPTS="-Xms256m -Xmx512m"